# Generated by Django 3.2.9 on 2024-06-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_remove_prodproduct_test_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodproduct',
            name='productSold',
            field=models.IntegerField(default=0),
        ),
    ]
