# Generated by Django 5.1.3 on 2024-12-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_person_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Message', models.TextField()),
                ('Creator_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='media/uploads/feeds')),
            ],
            options={
                'db_table': 'feed',
            },
        ),
    ]
