# Generated by Django 5.1.3 on 2024-12-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0008_auto_20230709_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=8000)),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='reply_comment_images')),
                ('commenter_id', models.IntegerField()),
                ('comment_id', models.IntegerField()),
                ('feed_id', models.IntegerField()),
            ],
        ),
    ]
